apiVersion: v1
kind: Service
metadata:
  name: {{ include "hoorific.fullname" . }}-inference
  labels:
    {{- include "hoorific.labels" . | nindent 4 }}
    app.kubernetes.io/component: inference
spec:
  type: {{ .Values.service.inference.type }}
  selector:
    {{- include "hoorific.selectorLabels" . | nindent 4 }}
  ports:
    - name: inference
      port: {{ .Values.service.inference.port }}
      targetPort: inference
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hoorific.fullname" . }}-management
  labels:
    {{- include "hoorific.labels" . | nindent 4 }}
    app.kubernetes.io/component: management
spec:
  type: {{ .Values.service.management.type }}
  selector:
    {{- include "hoorific.selectorLabels" . | nindent 4 }}
  ports:
    - name: management
      port: {{ .Values.service.management.port }}
      targetPort: management
      protocol: TCP
