import { useRef, useState } from 'preact/hooks';
import { api, APIError } from './api';

export function Playground() {
  const [operation, setOperation] = useState('chat'); const [path, setPath] = useState('/playground/v1/chat/completions');
  const [payload, setPayload] = useState('{\n  "model": "",\n  "messages": [{"role":"user","content":""}],\n  "stream": true\n}'); const [file, setFile] = useState<File>(); const [output, setOutput] = useState(''); const [mediaURL, setMediaURL] = useState(''); const [error, setError] = useState<unknown>(); const [running, setRunning] = useState(false); const controller = useRef<AbortController>();
  const start = async (event: Event) => { event.preventDefault(); setError(undefined); setOutput(''); setMediaURL(''); let body: unknown; try { body = JSON.parse(payload); } catch { setError(new Error('Request JSON is invalid.')); return; } if (file) { try { const data = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error ?? new Error('File read failed')); reader.readAsDataURL(file); }); if (body && typeof body === 'object') body = {...body, input_file: {name:file.name, media_type:file.type, data}}; } catch (e) { setError(e); return; } } const abort = new AbortController(); controller.current = abort; setRunning(true); try { await api.stream(path, body, abort.signal, chunk => { setOutput(current => current + chunk); const match = chunk.match(/https?:\/\/[^\s\"']+|data:(?:image|audio|video)\/[^;,]+;base64,[A-Za-z0-9+/=]+/); if (match) setMediaURL(match[0]); }); } catch (e) { if (!(e instanceof DOMException && e.name === 'AbortError')) setError(e); } finally { setRunning(false); controller.current = undefined; } };
  return <section class="playground"><h1>Inference playground</h1><p class="muted">Requests run through the authenticated gateway and use the same admission, policy and cancellation path as clients. File contents stay in this tab and are sent only when you submit.</p><form onSubmit={start}><label class="field"><span>Operation</span><select value={operation} onChange={e => { const next = (e.currentTarget as HTMLSelectElement).value; setOperation(next); if (next === 'chat') setPath('/playground/v1/chat/completions'); else if (next === 'responses') setPath('/playground/v1/responses'); else if (next === 'image') setPath('/playground/v1/images/generations'); else if (next === 'audio') setPath('/playground/v1/audio/speech'); else if (next === 'video') setPath('/playground/v1/videos'); }}><option value="chat">Chat generation</option><option value="responses">Responses</option><option value="image">Image generation</option><option value="audio">Audio speech</option><option value="video">Video job</option></select></label><label class="field"><span>Gateway operation path</span><input value={path} onInput={e => setPath((e.currentTarget as HTMLInputElement).value)} /></label><label class="field"><span>JSON request</span><textarea class="play-editor" value={payload} onInput={e => setPayload((e.currentTarget as HTMLTextAreaElement).value)} /></label><label class="field"><span>Optional input media/document</span><input type="file" onChange={e => setFile((e.currentTarget as HTMLInputElement).files?.[0])} /></label><div class="form-actions"><button disabled={running}>{running ? 'Streaming…' : 'Send request'}</button>{running && <button type="button" class="danger" onClick={() => controller.current?.abort()}>Cancel</button>}</div></form>{error && <div class="notice error" role="alert">{error instanceof APIError ? error.message : String(error)}</div>}<div class="stream-output" aria-live="polite"><h2>Stream output</h2><pre>{output || (running ? 'Waiting for events…' : 'No output yet.')}</pre>{mediaURL && (operation === 'image' ? <img class="media-result" src={mediaURL} alt="Generated image returned by provider" /> : operation === 'audio' ? <audio controls src={mediaURL} /> : operation === 'video' ? <video controls src={mediaURL} /> : null)}</div></section>;
}
